/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.*;

/**
 *
 * @author Admin1
 */
public class BadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form BadConsequenceView
     */
    
    BadConsequence badConsequenceModel;
    public BadConsequenceView() {
        initComponents();
    }

    public void setBadConsequence(BadConsequence bc){
        badConsequenceModel=bc;
        if(badConsequenceModel!=null){
            if(badConsequenceModel.getDeath()){
                jLabelmuerte.setText("Muerte");
                jLabelnVisibles.setText("");
                jLabelnOcultos.setText("");
                jLabelspOcultos.setText("");
                jLabelspVisibles.setText("");
                jLabelTextBadConsequence.setText(badConsequenceModel.getText());
            } else{
                
                jLabelTextBadConsequence.setText(badConsequenceModel.getText());
                jLabelLostLevels.setText(Integer.toString(badConsequenceModel.getLevels()));
                if(badConsequenceModel.getNVisibleTreasures()!=0&&badConsequenceModel.getNHiddenTreasures()!=0){
                    jLabelnVisibles.setText("Tesoros Visibles: "+Integer.toString(badConsequenceModel.getNVisibleTreasures()));
                    jLabelnOcultos.setText("Tesoros Ocultos: "+Integer.toString(badConsequenceModel.getNHiddenTreasures()));
                }
                else{
                    if(badConsequenceModel.getSpecificVisibleTreasures()!=null)
                        jLabelspVisibles.setText("Tesoros Visibles: "+badConsequenceModel.getSpecificVisibleTreasures().toString());
                    if(badConsequenceModel.getSpecificHiddenTreasures()!=null)
                        jLabelspOcultos.setText("Tesoros Ocultos: "+badConsequenceModel.getSpecificHiddenTreasures().toString());
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BadConsequenceTitle = new javax.swing.JLabel();
        textBadConsequence = new javax.swing.JLabel();
        lostLevels = new javax.swing.JLabel();
        jLabelLostLevels = new javax.swing.JLabel();
        jLabelTextBadConsequence = new javax.swing.JLabel();
        jLabelmuerte = new javax.swing.JLabel();
        jLabelnVisibles = new javax.swing.JLabel();
        jLabelnOcultos = new javax.swing.JLabel();
        jLabelspVisibles = new javax.swing.JLabel();
        jLabelspOcultos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        BadConsequenceTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BadConsequenceTitle.setText("Bad Consequence");

        textBadConsequence.setText("Mal Rollo:");

        lostLevels.setText("Niveles Perdidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lostLevels)
                            .addComponent(textBadConsequence))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTextBadConsequence)
                            .addComponent(jLabelLostLevels)))
                    .addComponent(BadConsequenceTitle)
                    .addComponent(jLabelnVisibles)
                    .addComponent(jLabelnOcultos)
                    .addComponent(jLabelspVisibles)
                    .addComponent(jLabelspOcultos)
                    .addComponent(jLabelmuerte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(BadConsequenceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBadConsequence)
                    .addComponent(jLabelTextBadConsequence))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lostLevels)
                    .addComponent(jLabelLostLevels))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelmuerte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnVisibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnOcultos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelspVisibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelspOcultos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BadConsequenceTitle;
    private javax.swing.JLabel jLabelLostLevels;
    private javax.swing.JLabel jLabelTextBadConsequence;
    private javax.swing.JLabel jLabelmuerte;
    private javax.swing.JLabel jLabelnOcultos;
    private javax.swing.JLabel jLabelnVisibles;
    private javax.swing.JLabel jLabelspOcultos;
    private javax.swing.JLabel jLabelspVisibles;
    private javax.swing.JLabel lostLevels;
    private javax.swing.JLabel textBadConsequence;
    // End of variables declaration//GEN-END:variables
}
