/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.BadConsequence;
import napakalaki.CombatResult;

/**
 *
 * @author Admin1
 */
public class PendingBadConsequence extends javax.swing.JPanel {

    /**
     * Creates new form pendingBadConsequence
     */
    
    
    BadConsequence pendingBadConsequenceModel;
    
    public PendingBadConsequence() {
        initComponents();
    }
    
    public BadConsequence getModel(){
        return pendingBadConsequenceModel;
    }
    
    
    public void setPendingBadConsequence(BadConsequence pbc){
        pendingBadConsequenceModel = pbc;
        jLabelnVisibles.setText(pendingBadConsequenceModel.getText());
        jLabelnOcultos.setText(pendingBadConsequenceModel.getText());
        if(pendingBadConsequenceModel.getSpecificVisibleTreasures()!=null)
            jLabelspVisibles.setText(pendingBadConsequenceModel.getSpecificVisibleTreasures().toString());
        if(pendingBadConsequenceModel.getSpecificHiddenTreasures()!=null)
            jLabelspOcultos.setText(pendingBadConsequenceModel.getSpecificHiddenTreasures().toString());
        
        
        //---------------------------//
//        NapakalakiView nView=new NapakalakiView();
//        combatResult=nView.napakalakiModel.developCombat();
//        if(combatResult==CombatResult.LOSE){
//            pendingBadConsequenceModel=pbc;
//            
//        }
        //--------------------------//
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelnVisibles = new javax.swing.JLabel();
        jLabelnOcultos = new javax.swing.JLabel();
        jLabelspVisibles = new javax.swing.JLabel();
        jLabelspOcultos = new javax.swing.JLabel();
        pendingBadConsequenceTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero Visibles");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero Ocultos");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Especificos Visibles");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Especificos Ocultos");

        jLabelnVisibles.setForeground(new java.awt.Color(255, 255, 255));

        jLabelnOcultos.setForeground(new java.awt.Color(255, 255, 255));

        jLabelspVisibles.setForeground(new java.awt.Color(255, 255, 255));

        jLabelspOcultos.setForeground(new java.awt.Color(255, 255, 255));

        pendingBadConsequenceTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pendingBadConsequenceTitle.setForeground(new java.awt.Color(255, 255, 255));
        pendingBadConsequenceTitle.setText("BAD CONSEQUENCE PENDIENTE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelspOcultos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelspVisibles)
                            .addComponent(jLabelnOcultos)
                            .addComponent(jLabelnVisibles)))
                    .addComponent(pendingBadConsequenceTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pendingBadConsequenceTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelnVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelnOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelspVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelspOcultos))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelnOcultos;
    private javax.swing.JLabel jLabelnVisibles;
    private javax.swing.JLabel jLabelspOcultos;
    private javax.swing.JLabel jLabelspVisibles;
    private javax.swing.JLabel pendingBadConsequenceTitle;
    // End of variables declaration//GEN-END:variables
}
