/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Prize;

/**
 *
 * @author Admin1
 */
public class PrizeView extends javax.swing.JPanel {

    /**
     * Creates new form PrizeView
     */
    Prize prizeModel;
    public PrizeView() {
        initComponents();
    }
    public void setPrize(Prize pr){
        prizeModel = pr;
        this.jLabelTreasuresGained.setText(Integer.toString(prizeModel.getTreasures()));
        this.jLabelLevelGained.setText(Integer.toString(prizeModel.getLevel()));
        
        
        repaint();
        revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prize = new javax.swing.JLabel();
        levelGained = new javax.swing.JLabel();
        TreasuresGained = new javax.swing.JLabel();
        jLabelLevelGained = new javax.swing.JLabel();
        jLabelTreasuresGained = new javax.swing.JLabel();

        prize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prize.setText("PREMIO");

        levelGained.setText("Niveles Ganados:");

        TreasuresGained.setText("Tesoros Ganados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TreasuresGained)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTreasuresGained))
                    .addComponent(prize)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelGained)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLevelGained)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelGained)
                    .addComponent(jLabelLevelGained))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TreasuresGained)
                    .addComponent(jLabelTreasuresGained))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TreasuresGained;
    private javax.swing.JLabel jLabelLevelGained;
    private javax.swing.JLabel jLabelTreasuresGained;
    private javax.swing.JLabel levelGained;
    private javax.swing.JLabel prize;
    // End of variables declaration//GEN-END:variables
}
